### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by imurreflection** [nickolayrusev/stremio-addon-exapp#1]
Hi, thank you for your availability on stremio. Please see that subtitles are not available on any of the videos played by this add-on. Request your kind consideration for fixing the same at the earliest.

**Comment by nickolayrusev** [comment]
hi, thanks for the feedback. initially the plugin is designed to work only with bulgarian subtitles but at the moment there is a problem with android version of stremio, desktop version works fine. what is your environment? os an preferred language?

**Comment by imurreflection** [comment]
The add-on works fine with both android 0.92 and 0.45.1  version optimised for Android TV. The link plays the movie fine. I am using 0.92 on Android Box running Android 7.1.2 and 0.45.1 running on Android 6.1. My preferred language is English but even if foreign audio is available but with English subtitles, it is just fine. Yours is a great add-on and thanks for wonderful work. Please see if you can incorporate English subtitles to make the add-on used by global users. If you need further information, please let me know

**Comment by nickolayrusev** [comment]
sorry but  may be  I will to stop the support of the plugin at the moment because the plugin needs funds for hosting, proxy and future improvements. The addon was designed for the stremio contest but somehow it didn't qualify for the prize pools , even in the community vote :) with the money of the prize pools I was planning to continue the development of the addon. thanks for support.

**Comment by imurreflection** [comment]
Mate, if you notice, the winners are mainly English speaking add-ons. To
ensure we attract attention, we need to take community along with us. May
be, this could be the hindrance for not scoring for the contest.However,
this does not mean that your content lacks quality. In fact, yours is
better than Zooqle for fetching links. I m sure if there is any Bulgarian
region contest, no one can beat your add-on. Please note that ee may face
denials at the beginning but quality always emerge as winner.

**Comment by nickolayrusev** [comment]
thanks for the kind words :) I will continue to do my best for the addon. I just need to find small financing for the proxy.  Are you part of the stremio dev team ?

**Comment by imurreflection** [comment]
No Mate, I am a common user but it was difficult to see an extremely talented developer giving up. I may not be able to support you financially but my best wishes and support is always with you

**Comment by nickolayrusev** [comment]
:) oh I don't want finance help from you :). The support from you is enough.
I'm not giving up, man. I will continue to work on the addon ;) Keep posting issues if you find any.
